- name: install nginx
  hosts: all
  become: yes
  tasks:
  - name: install ngnix
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start ngnix
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes