- name: variables
  hosts: localhost
  become: yes
  vars:
    Course: "Terraform"
    Trainer: "Siva"
    Duration: "3.5 months"
  tasks:
  - name: override variables
    vars:
      Course: "DevOps" 
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}} from {{Trainer}} with {{Duration}}"

  - name: print info
    ansible.builtin.debug:   
      msg: "Hi, I am learning {{Course}} from {{Trainer}} with {{Duration}}"