- name: data types
  hosts: localhost
  vars:
    course: "Devops with AWS"
    Tools:
    - docker
    - kuberneties
    - terraform
    - ansible
    Experience:
      Deevops: 3
      AWS: 2
      Docker: 1
    Realproject: true
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Course: {{course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, is real project: {{Realproject}}"