- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: user exist or not
    ansible.builtin.command: id expence
    register: USER
    ignore_errors: true

  - name: print user information
    ansible.builtin.debug:
      msg: "user info: {{USER}}"

  - name: create user
    ansible.builtin.command: useradd expence
    when: USER.rc != 0

  - name: user create or not
    ansible.builtin.debug:
      msg: user created

  - name: say hello
    ansible.builtin.debug:
     msg: "Hello" 
