- name: Default Value
  hosts: localhost
  tasks:
  - name: Print Default Value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

- name: Upper case
  hosts: localhost
  vars: 
    greeting: "Hello Good Morning"
  tasks:
    - name: convert into upper case
      ansible.builtin.debug:
        msg: "{{greeting | upper}}"