- name: install packages
  hosts: web
  bacome: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - mysql
    - postfix
