- name: instal packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"

  loop:
  - {name: 'nginx' , state: 'latest' }
  - {name: 'mysql' , state: 'absent'}
  - {name: 'postfix' , state: 'absent'}